config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'static_pages#home'
  resources :products, only: [:index,:show]
  get 'static_pages/about'
  get 'static_pages/member'
  get 'static_pages/member_recruit'
  get 'static_pages/parners'
  resources :blogs, only: :index
  post 'feedbacks/create' => 'feedbacks#create'
  get 'inquirys' => 'inquirys#index'              # 入力画面
  get 'inquirys/confirm' => redirect("/inquirys")
  get 'inquirys/thanks' => redirect("/inquirys")
  post 'inquirys/confirm' => 'inquirys#confirm'   # 確認画面
  post 'inquirys/thanks' => 'inquirys#thanks'     # 送信完了画面
  resources :countries, only: :show
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin_flg?
      can :access, :rails_admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
      # user ||= User.new # guest user (not logged in)
      # if user.admin?
      #   can :manage, :all
      # else
      # end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/connect_tag.rb
class ConnectTag < ApplicationRecord
  belongs_to :product
  belongs_to :tag
end

app/models/country.rb
class Country < ApplicationRecord
	has_many :products
	mount_uploader :flag_pic, ImageUploader
	mount_uploader :show_pic, ImageUploader
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  validates :body, presence: true
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  include ActiveModel::Model

  attr_accessor :name, :email, :phone, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
  validates :phone, :presence => {:message => '電話番号を入力してください'}
end

app/models/period.rb
class Period < ApplicationRecord
	has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :connect_tags
	has_many :tags, through: :connect_tags
	belongs_to :country
	belongs_to :period

	def create_period
	 all_period = ["2～3週間","2ヶ月以上","3ヶ月以上","半年以上","約1年"]
	 return all_period
	end

	def create_country
     all_country = ["シンガポール","ベトナム","カンボジア","インドネシア","フィリピン","マレーシア","タイ","ミャンマー","イスラエル","インド","スリランカ","南アフリカ","中国","台湾","メキシコ","エストニア","オーストラリア","アメリカ"]
     return all_country
	end

	mount_uploader :slider_photo1, ImageUploader
	mount_uploader :slider_photo2, ImageUploader
	mount_uploader :slider_photo3, ImageUploader
	mount_uploader :slider_photo4, ImageUploader
	mount_uploader :slider_photo5, ImageUploader
	mount_uploader :slider_photo6, ImageUploader
	mount_uploader :slider_photo7, ImageUploader
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :connect_tags
	has_many :products, through: :connect_tags
    accepts_nested_attributes_for :connect_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    # productsテーブルから最新順に作品を２０件取得する
    @blogs = Blog.order('id ASC').limit(30)
    @countries = Country.where.not(show_pic: nil, flag_pic: nil)
  end
end

app/controllers/inquirys_controller.rb
class InquirysController < ApplicationController
  def index
    # 入力画面を表示
    @inquiry = Inquiry.new
    render :action => 'index'
  end

  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.valid?
      # OK。確認画面を表示
      render :action => 'confirm'
    else
      # NG。入力画面を再表示
      render :action => 'index'
    end
  end

  def thanks
    # メール送信
    @inquiry = Inquiry.new(inquiry_params)
    InquiryMailer.received_email(@inquiry).deliver
    render :action => 'thanks'
  end

  private
    def inquiry_params
    	params.require(:inquiry).permit(
      :name, :email, :phone, :message
    )
    end
end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :create_info , only: [:index, :show]

  def create_info
    @product = Product.order('id ASC').limit(40)
    @periods = Period.order('id ASC')
    @countrys = Country.order('id ASC')
  end

  def index
    @products = Product.order('id DESC').where.not(slider_photo1: nil,id: 32).limit(3)
  end

  def show
    @product = Product.find(params[:id])
    @relation_products = Product.order('id ASC').limit(5)
    @countries = Country.order('id ASC').limit(20)
    @connect_tags = @product.connect_tags
    @spn_product = Product.find(42)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/inquirys_helper.rb
module InquirysHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/blogs/index.html.erb
 <main class="mt-5 all_top">
<!--Main container-->
    <!--Grid row-->
      <%= render 'common/countryinfo.html.erb' %>
      </div>

     <div class="gray-content">
      </div>
<!--Main container-->

   <div class="gray-content">
      </div>

</main>
<!--Main layout-->

app/views/blogs/show.html.erb
<div id="main_cnt_wrapper" class="all_top">
    <div id="yjContentsBody">
      <div class="yjContainer">
        <span class="yjGuid"><a id="yjContentsStart" name="yjContentsStart"></a><img alt="ここから本文です" height="1" src="http://i.yimg.jp/yui/jp/tmpl/1.1.0/audionav.gif" width="1"></span>
        <div id="yjMain">
          <article class="section">
            <div class="container">
              <header class="header header--section">
                <h2 class="text-middle">
                  <i class="icon-movie color-gray-light"></i><%= @blog.user_name %>
                </h2>
              </header>
              <h2 class="text-last">
                  <i class="i"></i><%= @blog.country %>
                </h2>
              </header>
              <div class="bussinness_content">
                 <header class="header header--section">
                  <h2 class="text-middle">
                   <i class="icon-movie color-gray-light"></i>業界：業種
                  </h2>
                 </header>
                  <div class="main_contents">
                    <i class="i"></i><%= @blog.industry %>
                  </div>
              </div>
              <div class="experience_content">
                 <header class="header header--section">
                  <h2 class="text-middle">
                   <i class="icon-movie color-gray-light"></i>状況
                  </h2>
                 </header>
                  <div class="main_contents">
                    <i class="i"></i><%= @blog.user_status %>
                  </div>
              </div>
              <div class="request_content">
                 <header class="header header--section">
                  <h2 class="text-middle">
                   <i class="icon-movie color-gray-light"></i>ブログ紙面
                 </header>
                  <div class="main_contents">
                    <i class="i"></i><%= @blog.body %>
                  </div>
              </div>

               <header class="header header--section">
                <h2 class="text-middle">

                  <i class="icon-movie color-gray-light"></i>みんなのレビュー
                </h2>
                </header>
            </div>
          </article>
        </div>
        <div id="yjSub">

app/views/inquirys/confirm.html.erb
<main class="mt-5 all_top">
  <!--Main container-->
 <div class="container">
  <!--Grid row-->
     <div class="page-header">
       <h1>お問い合わせ内容確認</h1>
         <h2>下記のお問い合わせ内容でお間違いがないかを確認の上送信ボタンを押してください</h2>
     </div>
     <%= form_for @inquiry, :url => inquirys_thanks_path do |f| %>
       <div class="form-group">
          <label for="exampleInputEmail1">お名前</label>
            <%= f.hidden_field :name %>
           <div class="confirm_box">
            <%= @inquiry.name %>
           </div>
       </div>

         <div class="form-group">
          <label for="exampleInputEmail1">Eメールアドレス</label>
          <span class="text-danger">（必須）</span>
            <%= f.hidden_field :email %>
          <div class="confirm_box">
            <%= @inquiry.email %>
         </div>


         <div class="form-group">
          <label for="exampleInputEmail1">電話番号</label>
          <span class="text-danger">（必須）</span>
            <%= f.hidden_field :phone %>
           <div class="confirm_box">
             <%= @inquiry.phone %>
           </div>
        </div>

       <div class="form-group">
          <label for="exampleFormControlTextarea1"">お問い合わせ内容</label>
            <%= f.hidden_field :message %>
            <div class="confirm_box">
              <%= simple_format(@inquiry.message) %>
            </div>
       </div>
        <strong><%= f.submit '送信', class: 'btn btn-lg btn-block send_bottom' %></strong>
        *送信ボタンを押すことは、個人情報の取扱いについてに同意したとみなします
       </div>
     <% end %>
  </div>
</main>

app/views/inquirys/index.html.erb
<main class="mt-2 all_top">
  <!--Main container-->
  <div class="container">
  <!--Grid row-->
 <%= form_for @inquiry, html: {id: 'form_id', class: 'was-validated'}, :url => inquirys_confirm_path ,novalidate: true do |f| %>
  <div class="page-header">
    <h1><strong><i class="fal fa-user-headset"></i></i>お問い合わせ</strong></h1>
  </div>
    <div class="form-group">
      <label for="exampleInputEmail1">お名前</label>
      <span class="text-danger">（必須）</span>
      <%= f.text_field :name, :class => 'form-control validate[required]',:id => 'validationCustom01',:placeholder => "お名前を入力してください",required: true %>
     <small class="text-muted">あなたの名前は他の誰とも共有しません。</small>
    </div>


    <div class="form-group">
      <label for="exampleInputEmail1">Eメールアドレス</label>
      <span class="text-danger">（必須）</span>
      <%= f.text_field :email, :class => 'form-control' ,:placeholder => "Eメールアドレスを入力してください",required: true%>
      <small class="text-muted">あなたのEメールアドレスは他の誰とも共有しません。</small>
    </div>



    <div class="form-group">
      <label for="exampleInputEmail1">電話番号</label>
      <span class="text-danger">（必須）</span>
      <%= f.text_field :phone, :class => 'form-control' ,:placeholder => "電話番号を入力してください",required: true%>
        <small class="text-muted">あなたの電話番号は他の誰とも共有しません。</small>
    </div>

    <div class="form-group">
      <label for="exampleFormControlTextarea1"">お問い合わせ内容</label>
      <%= f.text_area :message, :class => 'form-control' ,:placeholder => "お問い合わせ内容を入力してください" ,:rows => "8",required: true%>
    </div>


  <strong><%= f.submit '確認', class: 'btn btn-lg btn-block send_bottom' %></strong>
<% end %>

 </div>
</main>

app/views/inquirys/thanks.html.erb
<main class="mt-5 all_top">
  <!--Main container-->
  <div class="container">
  <!--Grid row-->
 <div class="row">
	<div class="col-md-12">
	  <img class="img-fluid" src="https://png.pngtree.com/png_detail/18/09/10/pngtree-single-bow-png-clipart_3335591.jpg">
	</div>
 </div>
<p>
  お問い合わせいただきありがとうございました。<br>
  お問い合わせ内容につきましては2~3営業日を頂きましてから返信させて頂きたいと思います。
</p>
</div>

app/views/products/index.html.erb
<!--Main layout-->
<main class="mt-10 all_top">

<!--Main container-->
<div class="container">
 <div class="row">

 <div class="col-md-12">
    <div class="search_pc">
      <%= render 'common/search.html.erb' %>
    </div>
    <div class="search_sp">
      <%= render 'common/searchsp.html.erb'%>
    </div>
    <script>
    $(document).ready( function(){
      var winW = $(window).width();
      var devW = 767;
      if (winW <= devW) {
        $(".search_sp").css({'display':'block'});
        $(".search_pc").css({'display':'none'});
        //767px以下の時の処理
      } else {
        $(".search_pc").css({'display':'block'});
        $(".search_sp").css({'display':'none'});
        //768pxより大きい時の処理
      }
     });

    $(window).on('load resize', function(){
      var winW = $(window).width();
      var devW = 767;
      if (winW <= devW) {
        $(".search_sp").css({'display':'block'});
        $(".search_pc").css({'display':'none'});
        //767px以下の時の処理
      } else {
        $(".search_pc").css({'display':'block'});
        $(".search_sp").css({'display':'none'});
        //768pxより大きい時の処理
      }
    });
    </script>
  </div>
  </div>
    <!--Grid row-->
    <div class="row">
         <% @products.each do |product| %>
            <div class="col-sm-6 col-md-4 search" data-category='CMS' data-tag='["<%= product.country.name %>","<%= product.period.id %>"]'>
          <a href="/products/<%= product.id %>">
            <div class="card top20">
            <div class="sub_pic">
               <img class="img-thumbnail" src="<%= product.slider_photo1 %>" alt="">
               <span><%= product.country.name %></span>
            </div>
             <div class="card-body">
                <div class="card-title_top">
                   <%= truncate(product.c_title, length: 58) do %>
                   <% end %>
                </div>
                 <div class="card-title">
                   <table class="media-card_table">
                      <tr class="card_C_name">
                       <th>会社名</th>
                         <td>
                         <%= truncate(product.c_name, length: 30) do %>
                         <% end %>
                         </td>
                       </tr>
                   </table>
                 </div>
                 <% product.connect_tags.each_with_index do |connect_tag,i| %>
                  <li class="tag_zone_index">
                   <%= connect_tag.tag.name %>
                   </li>
                   <%  break if i== 2 %>
                 <% end %>
              </div>
            </div>
          </a>
          <!--/.Card-->
          </div>
         <% end %>
    <!--Grid column-->
    </div>
       <script>
            //絞り込み検索機能
              var searchBox = '.search-boxs'; // 絞り込む項目を選択するエリア
              var listItem = '.search';   // 絞り込み対象のアイテム
              var hideClass = 'is-hide';     // 絞り込み対象外の場合に付与されるclass名

              $(function() {
                  // 絞り込み項目を変更した時
                  $(document).on('change', searchBox + ' input', function() {
                    setTimeout(function(){
                      search_filter();
                    },1000);
                  });
              });

              /**
               * リストの絞り込みを行う
               */
              function search_filter() {
                  check_conunt = 0
                  // 非表示状態を解除
                  $(listItem).removeClass(hideClass);
                  for (var i = 0; i < $(searchBox).length; i++) {
                      var name = $(searchBox).eq(i).find('input').attr('name');
                      // 選択されている項目を取得
                      var searchData = get_selected_input_items(name);
                      // 選択されている項目がない、またはALLを選択している場合は飛ばす
                      if(searchData.length === 0 || searchData[0] === '') {
                          continue;
                      }
                      // リスト内の各アイテムをチェック
                      for (var j = 0; j < $(listItem).length; j++) {
                        // console.log($(listItem).length);
                          // アイテムに設定している項目を取得
                          //引数でタグとカテゴリをget_setting_values_in_itemまで渡している
                          var itemData = get_setting_values_in_item($(listItem).eq(j), name);
                          console.log(itemData);
                          // 絞り込み対象かどうかを調べる
                          var check = array_match_check(itemData, searchData);
                          if(!check) {
                            $(listItem).eq(j).addClass(hideClass);
                          }
                      }
                  }
              }

              /**
               * inputで選択されている値の一覧を取得する
               * @param  {String} name 対象にするinputのname属性の値
               * @return {Array}       選択されているinputのvalue属性の値
               */
              function get_selected_input_items(name) {
                  var searchData = [];
                  $('[name=' + name + ']:checked').each(function() {
                      searchData.push($(this).val());
                  });
                  // console.log(searchData);
                  return searchData;
              }

              /**
               * リスト内のアイテムに設定している値の一覧を取得する
               * @param  {Object} target 対象にするアイテムのjQueryオブジェクト
               * @param  {String} data   対象にするアイテムのdata属性の名前
               * @return {Array}         対象にするアイテムのdata属性の値
               */
              function get_setting_values_in_item(target,data) {
                  var itemData = target.data(data);
                  if(!Array.isArray(itemData)) {
                      itemData = [itemData];
                  }
                  // console.log(itemData);
                  return itemData;
              }

              /**
               * 2つの配列内で一致する文字列があるかどうかを調べる
               * @param  {Array} arr1 調べる配列1
               * @param  {Array} arr2 調べる配列2
               * @return {Boolean}    一致する値があるかどうか
               */
              function array_match_check(arr1, arr2) {
                  // 絞り込み対象かどうかを調べる
                  var arrCheck = false;
                  for (var i = 0; i < arr1.length; i++) {
                      if(arr2.indexOf(arr1[i]) >= 0) {
                          arrCheck = true;
                          break;
                      }
                  }
                   // console.log(arrCheck);
                  return arrCheck;
              }
            </script>
<!--Grid row-->
    </div>
<!--Main container-->
</main>
<!--Main layout-->